// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lns_contract.proto

package types // import "github.com/33cn/plugin/plugin/dapp/lns/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/33cn/chain33/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LnsAction struct {
	// Types that are valid to be assigned to Value:
	//	*LnsAction_Open
	//	*LnsAction_DepositChannel
	//	*LnsAction_WithdrawChannel
	//	*LnsAction_Close
	//	*LnsAction_UpdateProof
	//	*LnsAction_Settle
	Value                isLnsAction_Value `protobuf_oneof:"value"`
	Ty                   int32             `protobuf:"varint,7,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LnsAction) Reset()         { *m = LnsAction{} }
func (m *LnsAction) String() string { return proto.CompactTextString(m) }
func (*LnsAction) ProtoMessage()    {}
func (*LnsAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{0}
}
func (m *LnsAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LnsAction.Unmarshal(m, b)
}
func (m *LnsAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LnsAction.Marshal(b, m, deterministic)
}
func (dst *LnsAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LnsAction.Merge(dst, src)
}
func (m *LnsAction) XXX_Size() int {
	return xxx_messageInfo_LnsAction.Size(m)
}
func (m *LnsAction) XXX_DiscardUnknown() {
	xxx_messageInfo_LnsAction.DiscardUnknown(m)
}

var xxx_messageInfo_LnsAction proto.InternalMessageInfo

type isLnsAction_Value interface {
	isLnsAction_Value()
}

type LnsAction_Open struct {
	Open *OpenChannel `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type LnsAction_DepositChannel struct {
	DepositChannel *DepositChannel `protobuf:"bytes,2,opt,name=depositChannel,proto3,oneof"`
}

type LnsAction_WithdrawChannel struct {
	WithdrawChannel *WithdrawChannel `protobuf:"bytes,3,opt,name=withdrawChannel,proto3,oneof"`
}

type LnsAction_Close struct {
	Close *CloseChannel `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type LnsAction_UpdateProof struct {
	UpdateProof *UpdateBalanceProof `protobuf:"bytes,5,opt,name=updateProof,proto3,oneof"`
}

type LnsAction_Settle struct {
	Settle *Settle `protobuf:"bytes,6,opt,name=settle,proto3,oneof"`
}

func (*LnsAction_Open) isLnsAction_Value() {}

func (*LnsAction_DepositChannel) isLnsAction_Value() {}

func (*LnsAction_WithdrawChannel) isLnsAction_Value() {}

func (*LnsAction_Close) isLnsAction_Value() {}

func (*LnsAction_UpdateProof) isLnsAction_Value() {}

func (*LnsAction_Settle) isLnsAction_Value() {}

func (m *LnsAction) GetValue() isLnsAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *LnsAction) GetOpen() *OpenChannel {
	if x, ok := m.GetValue().(*LnsAction_Open); ok {
		return x.Open
	}
	return nil
}

func (m *LnsAction) GetDepositChannel() *DepositChannel {
	if x, ok := m.GetValue().(*LnsAction_DepositChannel); ok {
		return x.DepositChannel
	}
	return nil
}

func (m *LnsAction) GetWithdrawChannel() *WithdrawChannel {
	if x, ok := m.GetValue().(*LnsAction_WithdrawChannel); ok {
		return x.WithdrawChannel
	}
	return nil
}

func (m *LnsAction) GetClose() *CloseChannel {
	if x, ok := m.GetValue().(*LnsAction_Close); ok {
		return x.Close
	}
	return nil
}

func (m *LnsAction) GetUpdateProof() *UpdateBalanceProof {
	if x, ok := m.GetValue().(*LnsAction_UpdateProof); ok {
		return x.UpdateProof
	}
	return nil
}

func (m *LnsAction) GetSettle() *Settle {
	if x, ok := m.GetValue().(*LnsAction_Settle); ok {
		return x.Settle
	}
	return nil
}

func (m *LnsAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LnsAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _LnsAction_OneofMarshaler, _LnsAction_OneofUnmarshaler, _LnsAction_OneofSizer, []interface{}{
		(*LnsAction_Open)(nil),
		(*LnsAction_DepositChannel)(nil),
		(*LnsAction_WithdrawChannel)(nil),
		(*LnsAction_Close)(nil),
		(*LnsAction_UpdateProof)(nil),
		(*LnsAction_Settle)(nil),
	}
}

func _LnsAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*LnsAction)
	// value
	switch x := m.Value.(type) {
	case *LnsAction_Open:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Open); err != nil {
			return err
		}
	case *LnsAction_DepositChannel:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DepositChannel); err != nil {
			return err
		}
	case *LnsAction_WithdrawChannel:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WithdrawChannel); err != nil {
			return err
		}
	case *LnsAction_Close:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Close); err != nil {
			return err
		}
	case *LnsAction_UpdateProof:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UpdateProof); err != nil {
			return err
		}
	case *LnsAction_Settle:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Settle); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("LnsAction.Value has unexpected type %T", x)
	}
	return nil
}

func _LnsAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*LnsAction)
	switch tag {
	case 1: // value.open
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OpenChannel)
		err := b.DecodeMessage(msg)
		m.Value = &LnsAction_Open{msg}
		return true, err
	case 2: // value.depositChannel
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DepositChannel)
		err := b.DecodeMessage(msg)
		m.Value = &LnsAction_DepositChannel{msg}
		return true, err
	case 3: // value.withdrawChannel
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WithdrawChannel)
		err := b.DecodeMessage(msg)
		m.Value = &LnsAction_WithdrawChannel{msg}
		return true, err
	case 4: // value.close
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CloseChannel)
		err := b.DecodeMessage(msg)
		m.Value = &LnsAction_Close{msg}
		return true, err
	case 5: // value.updateProof
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateBalanceProof)
		err := b.DecodeMessage(msg)
		m.Value = &LnsAction_UpdateProof{msg}
		return true, err
	case 6: // value.settle
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Settle)
		err := b.DecodeMessage(msg)
		m.Value = &LnsAction_Settle{msg}
		return true, err
	default:
		return false, nil
	}
}

func _LnsAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*LnsAction)
	// value
	switch x := m.Value.(type) {
	case *LnsAction_Open:
		s := proto.Size(x.Open)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LnsAction_DepositChannel:
		s := proto.Size(x.DepositChannel)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LnsAction_WithdrawChannel:
		s := proto.Size(x.WithdrawChannel)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LnsAction_Close:
		s := proto.Size(x.Close)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LnsAction_UpdateProof:
		s := proto.Size(x.UpdateProof)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LnsAction_Settle:
		s := proto.Size(x.Settle)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TokenCanonicalId struct {
	Chain                string   `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	IssueContract        string   `protobuf:"bytes,2,opt,name=issueContract,proto3" json:"issueContract,omitempty"`
	TokenSymbol          string   `protobuf:"bytes,3,opt,name=tokenSymbol,proto3" json:"tokenSymbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenCanonicalId) Reset()         { *m = TokenCanonicalId{} }
func (m *TokenCanonicalId) String() string { return proto.CompactTextString(m) }
func (*TokenCanonicalId) ProtoMessage()    {}
func (*TokenCanonicalId) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{1}
}
func (m *TokenCanonicalId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenCanonicalId.Unmarshal(m, b)
}
func (m *TokenCanonicalId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenCanonicalId.Marshal(b, m, deterministic)
}
func (dst *TokenCanonicalId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenCanonicalId.Merge(dst, src)
}
func (m *TokenCanonicalId) XXX_Size() int {
	return xxx_messageInfo_TokenCanonicalId.Size(m)
}
func (m *TokenCanonicalId) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenCanonicalId.DiscardUnknown(m)
}

var xxx_messageInfo_TokenCanonicalId proto.InternalMessageInfo

func (m *TokenCanonicalId) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *TokenCanonicalId) GetIssueContract() string {
	if m != nil {
		return m.IssueContract
	}
	return ""
}

func (m *TokenCanonicalId) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

type OpenChannel struct {
	IssueContract        string   `protobuf:"bytes,1,opt,name=issueContract,proto3" json:"issueContract,omitempty"`
	TokenSymbol          string   `protobuf:"bytes,2,opt,name=tokenSymbol,proto3" json:"tokenSymbol,omitempty"`
	Partner              string   `protobuf:"bytes,3,opt,name=partner,proto3" json:"partner,omitempty"`
	SettleTimeout        int32    `protobuf:"varint,4,opt,name=settleTimeout,proto3" json:"settleTimeout,omitempty"`
	Amount               int64    `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenChannel) Reset()         { *m = OpenChannel{} }
func (m *OpenChannel) String() string { return proto.CompactTextString(m) }
func (*OpenChannel) ProtoMessage()    {}
func (*OpenChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{2}
}
func (m *OpenChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenChannel.Unmarshal(m, b)
}
func (m *OpenChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenChannel.Marshal(b, m, deterministic)
}
func (dst *OpenChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenChannel.Merge(dst, src)
}
func (m *OpenChannel) XXX_Size() int {
	return xxx_messageInfo_OpenChannel.Size(m)
}
func (m *OpenChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenChannel.DiscardUnknown(m)
}

var xxx_messageInfo_OpenChannel proto.InternalMessageInfo

func (m *OpenChannel) GetIssueContract() string {
	if m != nil {
		return m.IssueContract
	}
	return ""
}

func (m *OpenChannel) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

func (m *OpenChannel) GetPartner() string {
	if m != nil {
		return m.Partner
	}
	return ""
}

func (m *OpenChannel) GetSettleTimeout() int32 {
	if m != nil {
		return m.SettleTimeout
	}
	return 0
}

func (m *OpenChannel) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DepositChannel struct {
	ChannelID            int64    `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TotalDeposit         int64    `protobuf:"varint,2,opt,name=totalDeposit,proto3" json:"totalDeposit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositChannel) Reset()         { *m = DepositChannel{} }
func (m *DepositChannel) String() string { return proto.CompactTextString(m) }
func (*DepositChannel) ProtoMessage()    {}
func (*DepositChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{3}
}
func (m *DepositChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositChannel.Unmarshal(m, b)
}
func (m *DepositChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositChannel.Marshal(b, m, deterministic)
}
func (dst *DepositChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositChannel.Merge(dst, src)
}
func (m *DepositChannel) XXX_Size() int {
	return xxx_messageInfo_DepositChannel.Size(m)
}
func (m *DepositChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositChannel.DiscardUnknown(m)
}

var xxx_messageInfo_DepositChannel proto.InternalMessageInfo

func (m *DepositChannel) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *DepositChannel) GetTotalDeposit() int64 {
	if m != nil {
		return m.TotalDeposit
	}
	return 0
}

type WithdrawChannel struct {
	ChannelID            int64                 `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Proof                *WithdrawConfirmProof `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	PartnerSignature     *types.Signature      `protobuf:"bytes,3,opt,name=partnerSignature,proto3" json:"partnerSignature,omitempty"`
	WithdrawerSignature  *types.Signature      `protobuf:"bytes,4,opt,name=withdrawerSignature,proto3" json:"withdrawerSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WithdrawChannel) Reset()         { *m = WithdrawChannel{} }
func (m *WithdrawChannel) String() string { return proto.CompactTextString(m) }
func (*WithdrawChannel) ProtoMessage()    {}
func (*WithdrawChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{4}
}
func (m *WithdrawChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawChannel.Unmarshal(m, b)
}
func (m *WithdrawChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawChannel.Marshal(b, m, deterministic)
}
func (dst *WithdrawChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawChannel.Merge(dst, src)
}
func (m *WithdrawChannel) XXX_Size() int {
	return xxx_messageInfo_WithdrawChannel.Size(m)
}
func (m *WithdrawChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawChannel.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawChannel proto.InternalMessageInfo

func (m *WithdrawChannel) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *WithdrawChannel) GetProof() *WithdrawConfirmProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *WithdrawChannel) GetPartnerSignature() *types.Signature {
	if m != nil {
		return m.PartnerSignature
	}
	return nil
}

func (m *WithdrawChannel) GetWithdrawerSignature() *types.Signature {
	if m != nil {
		return m.WithdrawerSignature
	}
	return nil
}

type WithdrawConfirmProof struct {
	ChannelID            int64    `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Withdrawer           string   `protobuf:"bytes,2,opt,name=withdrawer,proto3" json:"withdrawer,omitempty"`
	TotalWithdraw        int64    `protobuf:"varint,3,opt,name=totalWithdraw,proto3" json:"totalWithdraw,omitempty"`
	ExpirationBlock      int64    `protobuf:"varint,4,opt,name=expirationBlock,proto3" json:"expirationBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawConfirmProof) Reset()         { *m = WithdrawConfirmProof{} }
func (m *WithdrawConfirmProof) String() string { return proto.CompactTextString(m) }
func (*WithdrawConfirmProof) ProtoMessage()    {}
func (*WithdrawConfirmProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{5}
}
func (m *WithdrawConfirmProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawConfirmProof.Unmarshal(m, b)
}
func (m *WithdrawConfirmProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawConfirmProof.Marshal(b, m, deterministic)
}
func (dst *WithdrawConfirmProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawConfirmProof.Merge(dst, src)
}
func (m *WithdrawConfirmProof) XXX_Size() int {
	return xxx_messageInfo_WithdrawConfirmProof.Size(m)
}
func (m *WithdrawConfirmProof) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawConfirmProof.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawConfirmProof proto.InternalMessageInfo

func (m *WithdrawConfirmProof) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *WithdrawConfirmProof) GetWithdrawer() string {
	if m != nil {
		return m.Withdrawer
	}
	return ""
}

func (m *WithdrawConfirmProof) GetTotalWithdraw() int64 {
	if m != nil {
		return m.TotalWithdraw
	}
	return 0
}

func (m *WithdrawConfirmProof) GetExpirationBlock() int64 {
	if m != nil {
		return m.ExpirationBlock
	}
	return 0
}

type WithdrawConfirmProofSigned struct {
	ChannelID            int64                 `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	WithdrawConfirmProof *WithdrawConfirmProof `protobuf:"bytes,2,opt,name=withdrawConfirmProof,proto3" json:"withdrawConfirmProof,omitempty"`
	PartnerSignature     *types.Signature      `protobuf:"bytes,3,opt,name=partnerSignature,proto3" json:"partnerSignature,omitempty"`
	WithdrawerSignature  *types.Signature      `protobuf:"bytes,4,opt,name=withdrawerSignature,proto3" json:"withdrawerSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WithdrawConfirmProofSigned) Reset()         { *m = WithdrawConfirmProofSigned{} }
func (m *WithdrawConfirmProofSigned) String() string { return proto.CompactTextString(m) }
func (*WithdrawConfirmProofSigned) ProtoMessage()    {}
func (*WithdrawConfirmProofSigned) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{6}
}
func (m *WithdrawConfirmProofSigned) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawConfirmProofSigned.Unmarshal(m, b)
}
func (m *WithdrawConfirmProofSigned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawConfirmProofSigned.Marshal(b, m, deterministic)
}
func (dst *WithdrawConfirmProofSigned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawConfirmProofSigned.Merge(dst, src)
}
func (m *WithdrawConfirmProofSigned) XXX_Size() int {
	return xxx_messageInfo_WithdrawConfirmProofSigned.Size(m)
}
func (m *WithdrawConfirmProofSigned) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawConfirmProofSigned.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawConfirmProofSigned proto.InternalMessageInfo

func (m *WithdrawConfirmProofSigned) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *WithdrawConfirmProofSigned) GetWithdrawConfirmProof() *WithdrawConfirmProof {
	if m != nil {
		return m.WithdrawConfirmProof
	}
	return nil
}

func (m *WithdrawConfirmProofSigned) GetPartnerSignature() *types.Signature {
	if m != nil {
		return m.PartnerSignature
	}
	return nil
}

func (m *WithdrawConfirmProofSigned) GetWithdrawerSignature() *types.Signature {
	if m != nil {
		return m.WithdrawerSignature
	}
	return nil
}

type TransferAdditionData struct {
	PaymentID            string   `protobuf:"bytes,1,opt,name=paymentID,proto3" json:"paymentID,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender               string   `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferAdditionData) Reset()         { *m = TransferAdditionData{} }
func (m *TransferAdditionData) String() string { return proto.CompactTextString(m) }
func (*TransferAdditionData) ProtoMessage()    {}
func (*TransferAdditionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{7}
}
func (m *TransferAdditionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferAdditionData.Unmarshal(m, b)
}
func (m *TransferAdditionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferAdditionData.Marshal(b, m, deterministic)
}
func (dst *TransferAdditionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferAdditionData.Merge(dst, src)
}
func (m *TransferAdditionData) XXX_Size() int {
	return xxx_messageInfo_TransferAdditionData.Size(m)
}
func (m *TransferAdditionData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferAdditionData.DiscardUnknown(m)
}

var xxx_messageInfo_TransferAdditionData proto.InternalMessageInfo

func (m *TransferAdditionData) GetPaymentID() string {
	if m != nil {
		return m.PaymentID
	}
	return ""
}

func (m *TransferAdditionData) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *TransferAdditionData) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *TransferAdditionData) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BalanceProof struct {
	Nonce                int64             `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TransferredAmount    int64             `protobuf:"varint,2,opt,name=transferredAmount,proto3" json:"transferredAmount,omitempty"`
	AdditionHash         []byte            `protobuf:"bytes,3,opt,name=additionHash,proto3" json:"additionHash,omitempty"`
	TokenCanonicalId     *TokenCanonicalId `protobuf:"bytes,4,opt,name=tokenCanonicalId,proto3" json:"tokenCanonicalId,omitempty"`
	ChannelID            int64             `protobuf:"varint,5,opt,name=channelID,proto3" json:"channelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BalanceProof) Reset()         { *m = BalanceProof{} }
func (m *BalanceProof) String() string { return proto.CompactTextString(m) }
func (*BalanceProof) ProtoMessage()    {}
func (*BalanceProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{8}
}
func (m *BalanceProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceProof.Unmarshal(m, b)
}
func (m *BalanceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceProof.Marshal(b, m, deterministic)
}
func (dst *BalanceProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceProof.Merge(dst, src)
}
func (m *BalanceProof) XXX_Size() int {
	return xxx_messageInfo_BalanceProof.Size(m)
}
func (m *BalanceProof) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceProof.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceProof proto.InternalMessageInfo

func (m *BalanceProof) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BalanceProof) GetTransferredAmount() int64 {
	if m != nil {
		return m.TransferredAmount
	}
	return 0
}

func (m *BalanceProof) GetAdditionHash() []byte {
	if m != nil {
		return m.AdditionHash
	}
	return nil
}

func (m *BalanceProof) GetTokenCanonicalId() *TokenCanonicalId {
	if m != nil {
		return m.TokenCanonicalId
	}
	return nil
}

func (m *BalanceProof) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

type CloseChannel struct {
	ChannelID            int64            `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	NonCloserBalancePf   *BalanceProof    `protobuf:"bytes,2,opt,name=nonCloserBalancePf,proto3" json:"nonCloserBalancePf,omitempty"`
	NonCloserSignature   *types.Signature `protobuf:"bytes,3,opt,name=nonCloserSignature,proto3" json:"nonCloserSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CloseChannel) Reset()         { *m = CloseChannel{} }
func (m *CloseChannel) String() string { return proto.CompactTextString(m) }
func (*CloseChannel) ProtoMessage()    {}
func (*CloseChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{9}
}
func (m *CloseChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseChannel.Unmarshal(m, b)
}
func (m *CloseChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseChannel.Marshal(b, m, deterministic)
}
func (dst *CloseChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseChannel.Merge(dst, src)
}
func (m *CloseChannel) XXX_Size() int {
	return xxx_messageInfo_CloseChannel.Size(m)
}
func (m *CloseChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseChannel.DiscardUnknown(m)
}

var xxx_messageInfo_CloseChannel proto.InternalMessageInfo

func (m *CloseChannel) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *CloseChannel) GetNonCloserBalancePf() *BalanceProof {
	if m != nil {
		return m.NonCloserBalancePf
	}
	return nil
}

func (m *CloseChannel) GetNonCloserSignature() *types.Signature {
	if m != nil {
		return m.NonCloserSignature
	}
	return nil
}

type UpdateBalanceProof struct {
	ChannelID            int64            `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	PartnerBalancePf     *BalanceProof    `protobuf:"bytes,2,opt,name=partnerBalancePf,proto3" json:"partnerBalancePf,omitempty"`
	PartnerSignature     *types.Signature `protobuf:"bytes,3,opt,name=partnerSignature,proto3" json:"partnerSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateBalanceProof) Reset()         { *m = UpdateBalanceProof{} }
func (m *UpdateBalanceProof) String() string { return proto.CompactTextString(m) }
func (*UpdateBalanceProof) ProtoMessage()    {}
func (*UpdateBalanceProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{10}
}
func (m *UpdateBalanceProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalanceProof.Unmarshal(m, b)
}
func (m *UpdateBalanceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalanceProof.Marshal(b, m, deterministic)
}
func (dst *UpdateBalanceProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalanceProof.Merge(dst, src)
}
func (m *UpdateBalanceProof) XXX_Size() int {
	return xxx_messageInfo_UpdateBalanceProof.Size(m)
}
func (m *UpdateBalanceProof) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalanceProof.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalanceProof proto.InternalMessageInfo

func (m *UpdateBalanceProof) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *UpdateBalanceProof) GetPartnerBalancePf() *BalanceProof {
	if m != nil {
		return m.PartnerBalancePf
	}
	return nil
}

func (m *UpdateBalanceProof) GetPartnerSignature() *types.Signature {
	if m != nil {
		return m.PartnerSignature
	}
	return nil
}

type Settle struct {
	ChannelID                int64    `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	SelfTransferredAmount    int64    `protobuf:"varint,2,opt,name=selfTransferredAmount,proto3" json:"selfTransferredAmount,omitempty"`
	PartnerTransferredAmount int64    `protobuf:"varint,3,opt,name=partnerTransferredAmount,proto3" json:"partnerTransferredAmount,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Settle) Reset()         { *m = Settle{} }
func (m *Settle) String() string { return proto.CompactTextString(m) }
func (*Settle) ProtoMessage()    {}
func (*Settle) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{11}
}
func (m *Settle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settle.Unmarshal(m, b)
}
func (m *Settle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settle.Marshal(b, m, deterministic)
}
func (dst *Settle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settle.Merge(dst, src)
}
func (m *Settle) XXX_Size() int {
	return xxx_messageInfo_Settle.Size(m)
}
func (m *Settle) XXX_DiscardUnknown() {
	xxx_messageInfo_Settle.DiscardUnknown(m)
}

var xxx_messageInfo_Settle proto.InternalMessageInfo

func (m *Settle) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *Settle) GetSelfTransferredAmount() int64 {
	if m != nil {
		return m.SelfTransferredAmount
	}
	return 0
}

func (m *Settle) GetPartnerTransferredAmount() int64 {
	if m != nil {
		return m.PartnerTransferredAmount
	}
	return 0
}

type Participant struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	TotalDeposit         int64    `protobuf:"varint,2,opt,name=totalDeposit,proto3" json:"totalDeposit,omitempty"`
	TotalWithdraw        int64    `protobuf:"varint,3,opt,name=totalWithdraw,proto3" json:"totalWithdraw,omitempty"`
	Nonce                int64    `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TransferredAmount    int64    `protobuf:"varint,5,opt,name=transferredAmount,proto3" json:"transferredAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Participant) Reset()         { *m = Participant{} }
func (m *Participant) String() string { return proto.CompactTextString(m) }
func (*Participant) ProtoMessage()    {}
func (*Participant) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{12}
}
func (m *Participant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participant.Unmarshal(m, b)
}
func (m *Participant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participant.Marshal(b, m, deterministic)
}
func (dst *Participant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participant.Merge(dst, src)
}
func (m *Participant) XXX_Size() int {
	return xxx_messageInfo_Participant.Size(m)
}
func (m *Participant) XXX_DiscardUnknown() {
	xxx_messageInfo_Participant.DiscardUnknown(m)
}

var xxx_messageInfo_Participant proto.InternalMessageInfo

func (m *Participant) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Participant) GetTotalDeposit() int64 {
	if m != nil {
		return m.TotalDeposit
	}
	return 0
}

func (m *Participant) GetTotalWithdraw() int64 {
	if m != nil {
		return m.TotalWithdraw
	}
	return 0
}

func (m *Participant) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Participant) GetTransferredAmount() int64 {
	if m != nil {
		return m.TransferredAmount
	}
	return 0
}

type Channel struct {
	IssueContract        string       `protobuf:"bytes,1,opt,name=issueContract,proto3" json:"issueContract,omitempty"`
	TokenSymbol          string       `protobuf:"bytes,2,opt,name=tokenSymbol,proto3" json:"tokenSymbol,omitempty"`
	ChannelID            int64        `protobuf:"varint,3,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TotalAmount          int64        `protobuf:"varint,4,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	State                int32        `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	Participant1         *Participant `protobuf:"bytes,6,opt,name=participant1,proto3" json:"participant1,omitempty"`
	Participant2         *Participant `protobuf:"bytes,7,opt,name=participant2,proto3" json:"participant2,omitempty"`
	Closer               string       `protobuf:"bytes,8,opt,name=closer,proto3" json:"closer,omitempty"`
	SettleBlockHeight    int64        `protobuf:"varint,9,opt,name=settleBlockHeight,proto3" json:"settleBlockHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{13}
}
func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (dst *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(dst, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetIssueContract() string {
	if m != nil {
		return m.IssueContract
	}
	return ""
}

func (m *Channel) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

func (m *Channel) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *Channel) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *Channel) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Channel) GetParticipant1() *Participant {
	if m != nil {
		return m.Participant1
	}
	return nil
}

func (m *Channel) GetParticipant2() *Participant {
	if m != nil {
		return m.Participant2
	}
	return nil
}

func (m *Channel) GetCloser() string {
	if m != nil {
		return m.Closer
	}
	return ""
}

func (m *Channel) GetSettleBlockHeight() int64 {
	if m != nil {
		return m.SettleBlockHeight
	}
	return 0
}

type ChannelCount struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelCount) Reset()         { *m = ChannelCount{} }
func (m *ChannelCount) String() string { return proto.CompactTextString(m) }
func (*ChannelCount) ProtoMessage()    {}
func (*ChannelCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{14}
}
func (m *ChannelCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelCount.Unmarshal(m, b)
}
func (m *ChannelCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelCount.Marshal(b, m, deterministic)
}
func (dst *ChannelCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelCount.Merge(dst, src)
}
func (m *ChannelCount) XXX_Size() int {
	return xxx_messageInfo_ChannelCount.Size(m)
}
func (m *ChannelCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelCount.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelCount proto.InternalMessageInfo

func (m *ChannelCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReqGetChannel struct {
	ChannelID            int64    `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetChannel) Reset()         { *m = ReqGetChannel{} }
func (m *ReqGetChannel) String() string { return proto.CompactTextString(m) }
func (*ReqGetChannel) ProtoMessage()    {}
func (*ReqGetChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{15}
}
func (m *ReqGetChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetChannel.Unmarshal(m, b)
}
func (m *ReqGetChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetChannel.Marshal(b, m, deterministic)
}
func (dst *ReqGetChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetChannel.Merge(dst, src)
}
func (m *ReqGetChannel) XXX_Size() int {
	return xxx_messageInfo_ReqGetChannel.Size(m)
}
func (m *ReqGetChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetChannel.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetChannel proto.InternalMessageInfo

func (m *ReqGetChannel) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

type ReceiptOpen struct {
	Opener               string   `protobuf:"bytes,1,opt,name=opener,proto3" json:"opener,omitempty"`
	Partner              string   `protobuf:"bytes,2,opt,name=partner,proto3" json:"partner,omitempty"`
	ChannelID            int64    `protobuf:"varint,3,opt,name=channelID,proto3" json:"channelID,omitempty"`
	InitialBalance       int64    `protobuf:"varint,4,opt,name=initialBalance,proto3" json:"initialBalance,omitempty"`
	ChainName            string   `protobuf:"bytes,5,opt,name=chainName,proto3" json:"chainName,omitempty"`
	IssueContract        string   `protobuf:"bytes,6,opt,name=issueContract,proto3" json:"issueContract,omitempty"`
	TokenSymbol          string   `protobuf:"bytes,7,opt,name=TokenSymbol,proto3" json:"TokenSymbol,omitempty"`
	SettleTimeOut        int32    `protobuf:"varint,8,opt,name=settleTimeOut,proto3" json:"settleTimeOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptOpen) Reset()         { *m = ReceiptOpen{} }
func (m *ReceiptOpen) String() string { return proto.CompactTextString(m) }
func (*ReceiptOpen) ProtoMessage()    {}
func (*ReceiptOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{16}
}
func (m *ReceiptOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptOpen.Unmarshal(m, b)
}
func (m *ReceiptOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptOpen.Marshal(b, m, deterministic)
}
func (dst *ReceiptOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptOpen.Merge(dst, src)
}
func (m *ReceiptOpen) XXX_Size() int {
	return xxx_messageInfo_ReceiptOpen.Size(m)
}
func (m *ReceiptOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptOpen.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptOpen proto.InternalMessageInfo

func (m *ReceiptOpen) GetOpener() string {
	if m != nil {
		return m.Opener
	}
	return ""
}

func (m *ReceiptOpen) GetPartner() string {
	if m != nil {
		return m.Partner
	}
	return ""
}

func (m *ReceiptOpen) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *ReceiptOpen) GetInitialBalance() int64 {
	if m != nil {
		return m.InitialBalance
	}
	return 0
}

func (m *ReceiptOpen) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *ReceiptOpen) GetIssueContract() string {
	if m != nil {
		return m.IssueContract
	}
	return ""
}

func (m *ReceiptOpen) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

func (m *ReceiptOpen) GetSettleTimeOut() int32 {
	if m != nil {
		return m.SettleTimeOut
	}
	return 0
}

type ReceiptDeposit struct {
	Chain                string   `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	IssueContract        string   `protobuf:"bytes,2,opt,name=issueContract,proto3" json:"issueContract,omitempty"`
	TokenSymbol          string   `protobuf:"bytes,3,opt,name=tokenSymbol,proto3" json:"tokenSymbol,omitempty"`
	ChannelID            int64    `protobuf:"varint,4,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TotalDeposit         int64    `protobuf:"varint,5,opt,name=totalDeposit,proto3" json:"totalDeposit,omitempty"`
	Depositor            string   `protobuf:"bytes,6,opt,name=depositor,proto3" json:"depositor,omitempty"`
	Partner              string   `protobuf:"bytes,7,opt,name=partner,proto3" json:"partner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptDeposit) Reset()         { *m = ReceiptDeposit{} }
func (m *ReceiptDeposit) String() string { return proto.CompactTextString(m) }
func (*ReceiptDeposit) ProtoMessage()    {}
func (*ReceiptDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{17}
}
func (m *ReceiptDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptDeposit.Unmarshal(m, b)
}
func (m *ReceiptDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptDeposit.Marshal(b, m, deterministic)
}
func (dst *ReceiptDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptDeposit.Merge(dst, src)
}
func (m *ReceiptDeposit) XXX_Size() int {
	return xxx_messageInfo_ReceiptDeposit.Size(m)
}
func (m *ReceiptDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptDeposit proto.InternalMessageInfo

func (m *ReceiptDeposit) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *ReceiptDeposit) GetIssueContract() string {
	if m != nil {
		return m.IssueContract
	}
	return ""
}

func (m *ReceiptDeposit) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

func (m *ReceiptDeposit) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *ReceiptDeposit) GetTotalDeposit() int64 {
	if m != nil {
		return m.TotalDeposit
	}
	return 0
}

func (m *ReceiptDeposit) GetDepositor() string {
	if m != nil {
		return m.Depositor
	}
	return ""
}

func (m *ReceiptDeposit) GetPartner() string {
	if m != nil {
		return m.Partner
	}
	return ""
}

type ReceiptWithdraw struct {
	ChannelID            int64    `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TotalWithdraw        int64    `protobuf:"varint,2,opt,name=totalWithdraw,proto3" json:"totalWithdraw,omitempty"`
	Withdrawer           string   `protobuf:"bytes,4,opt,name=withdrawer,proto3" json:"withdrawer,omitempty"`
	Partner              string   `protobuf:"bytes,5,opt,name=partner,proto3" json:"partner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptWithdraw) Reset()         { *m = ReceiptWithdraw{} }
func (m *ReceiptWithdraw) String() string { return proto.CompactTextString(m) }
func (*ReceiptWithdraw) ProtoMessage()    {}
func (*ReceiptWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{18}
}
func (m *ReceiptWithdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptWithdraw.Unmarshal(m, b)
}
func (m *ReceiptWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptWithdraw.Marshal(b, m, deterministic)
}
func (dst *ReceiptWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptWithdraw.Merge(dst, src)
}
func (m *ReceiptWithdraw) XXX_Size() int {
	return xxx_messageInfo_ReceiptWithdraw.Size(m)
}
func (m *ReceiptWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptWithdraw proto.InternalMessageInfo

func (m *ReceiptWithdraw) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *ReceiptWithdraw) GetTotalWithdraw() int64 {
	if m != nil {
		return m.TotalWithdraw
	}
	return 0
}

func (m *ReceiptWithdraw) GetWithdrawer() string {
	if m != nil {
		return m.Withdrawer
	}
	return ""
}

func (m *ReceiptWithdraw) GetPartner() string {
	if m != nil {
		return m.Partner
	}
	return ""
}

type ReceiptClose struct {
	TokenCanonicalId     *TokenCanonicalId `protobuf:"bytes,1,opt,name=tokenCanonicalId,proto3" json:"tokenCanonicalId,omitempty"`
	ChannelID            int64             `protobuf:"varint,2,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Closer               string            `protobuf:"bytes,3,opt,name=closer,proto3" json:"closer,omitempty"`
	Partner              string            `protobuf:"bytes,4,opt,name=partner,proto3" json:"partner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReceiptClose) Reset()         { *m = ReceiptClose{} }
func (m *ReceiptClose) String() string { return proto.CompactTextString(m) }
func (*ReceiptClose) ProtoMessage()    {}
func (*ReceiptClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{19}
}
func (m *ReceiptClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptClose.Unmarshal(m, b)
}
func (m *ReceiptClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptClose.Marshal(b, m, deterministic)
}
func (dst *ReceiptClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptClose.Merge(dst, src)
}
func (m *ReceiptClose) XXX_Size() int {
	return xxx_messageInfo_ReceiptClose.Size(m)
}
func (m *ReceiptClose) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptClose.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptClose proto.InternalMessageInfo

func (m *ReceiptClose) GetTokenCanonicalId() *TokenCanonicalId {
	if m != nil {
		return m.TokenCanonicalId
	}
	return nil
}

func (m *ReceiptClose) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *ReceiptClose) GetCloser() string {
	if m != nil {
		return m.Closer
	}
	return ""
}

func (m *ReceiptClose) GetPartner() string {
	if m != nil {
		return m.Partner
	}
	return ""
}

type ReceiptUpdate struct {
	TokenCanonicalId     *TokenCanonicalId `protobuf:"bytes,1,opt,name=tokenCanonicalId,proto3" json:"tokenCanonicalId,omitempty"`
	Updater              string            `protobuf:"bytes,2,opt,name=updater,proto3" json:"updater,omitempty"`
	Partner              string            `protobuf:"bytes,3,opt,name=partner,proto3" json:"partner,omitempty"`
	ChannelID            int64             `protobuf:"varint,4,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Nonce                int64             `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReceiptUpdate) Reset()         { *m = ReceiptUpdate{} }
func (m *ReceiptUpdate) String() string { return proto.CompactTextString(m) }
func (*ReceiptUpdate) ProtoMessage()    {}
func (*ReceiptUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{20}
}
func (m *ReceiptUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptUpdate.Unmarshal(m, b)
}
func (m *ReceiptUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptUpdate.Marshal(b, m, deterministic)
}
func (dst *ReceiptUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptUpdate.Merge(dst, src)
}
func (m *ReceiptUpdate) XXX_Size() int {
	return xxx_messageInfo_ReceiptUpdate.Size(m)
}
func (m *ReceiptUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptUpdate proto.InternalMessageInfo

func (m *ReceiptUpdate) GetTokenCanonicalId() *TokenCanonicalId {
	if m != nil {
		return m.TokenCanonicalId
	}
	return nil
}

func (m *ReceiptUpdate) GetUpdater() string {
	if m != nil {
		return m.Updater
	}
	return ""
}

func (m *ReceiptUpdate) GetPartner() string {
	if m != nil {
		return m.Partner
	}
	return ""
}

func (m *ReceiptUpdate) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *ReceiptUpdate) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type ReceiptSettle struct {
	TokenCanonicalId     *TokenCanonicalId `protobuf:"bytes,1,opt,name=tokenCanonicalId,proto3" json:"tokenCanonicalId,omitempty"`
	ChannelID            int64             `protobuf:"varint,2,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Participant1         string            `protobuf:"bytes,3,opt,name=participant1,proto3" json:"participant1,omitempty"`
	TransferredAmount1   int64             `protobuf:"varint,4,opt,name=transferredAmount1,proto3" json:"transferredAmount1,omitempty"`
	Participant2         string            `protobuf:"bytes,5,opt,name=participant2,proto3" json:"participant2,omitempty"`
	TransferredAmount2   int64             `protobuf:"varint,6,opt,name=transferredAmount2,proto3" json:"transferredAmount2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReceiptSettle) Reset()         { *m = ReceiptSettle{} }
func (m *ReceiptSettle) String() string { return proto.CompactTextString(m) }
func (*ReceiptSettle) ProtoMessage()    {}
func (*ReceiptSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_lns_contract_3042a6b524479e87, []int{21}
}
func (m *ReceiptSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptSettle.Unmarshal(m, b)
}
func (m *ReceiptSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptSettle.Marshal(b, m, deterministic)
}
func (dst *ReceiptSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptSettle.Merge(dst, src)
}
func (m *ReceiptSettle) XXX_Size() int {
	return xxx_messageInfo_ReceiptSettle.Size(m)
}
func (m *ReceiptSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptSettle.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptSettle proto.InternalMessageInfo

func (m *ReceiptSettle) GetTokenCanonicalId() *TokenCanonicalId {
	if m != nil {
		return m.TokenCanonicalId
	}
	return nil
}

func (m *ReceiptSettle) GetChannelID() int64 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *ReceiptSettle) GetParticipant1() string {
	if m != nil {
		return m.Participant1
	}
	return ""
}

func (m *ReceiptSettle) GetTransferredAmount1() int64 {
	if m != nil {
		return m.TransferredAmount1
	}
	return 0
}

func (m *ReceiptSettle) GetParticipant2() string {
	if m != nil {
		return m.Participant2
	}
	return ""
}

func (m *ReceiptSettle) GetTransferredAmount2() int64 {
	if m != nil {
		return m.TransferredAmount2
	}
	return 0
}

func init() {
	proto.RegisterType((*LnsAction)(nil), "types.LnsAction")
	proto.RegisterType((*TokenCanonicalId)(nil), "types.TokenCanonicalId")
	proto.RegisterType((*OpenChannel)(nil), "types.OpenChannel")
	proto.RegisterType((*DepositChannel)(nil), "types.DepositChannel")
	proto.RegisterType((*WithdrawChannel)(nil), "types.WithdrawChannel")
	proto.RegisterType((*WithdrawConfirmProof)(nil), "types.WithdrawConfirmProof")
	proto.RegisterType((*WithdrawConfirmProofSigned)(nil), "types.WithdrawConfirmProofSigned")
	proto.RegisterType((*TransferAdditionData)(nil), "types.TransferAdditionData")
	proto.RegisterType((*BalanceProof)(nil), "types.BalanceProof")
	proto.RegisterType((*CloseChannel)(nil), "types.CloseChannel")
	proto.RegisterType((*UpdateBalanceProof)(nil), "types.UpdateBalanceProof")
	proto.RegisterType((*Settle)(nil), "types.Settle")
	proto.RegisterType((*Participant)(nil), "types.Participant")
	proto.RegisterType((*Channel)(nil), "types.Channel")
	proto.RegisterType((*ChannelCount)(nil), "types.ChannelCount")
	proto.RegisterType((*ReqGetChannel)(nil), "types.ReqGetChannel")
	proto.RegisterType((*ReceiptOpen)(nil), "types.ReceiptOpen")
	proto.RegisterType((*ReceiptDeposit)(nil), "types.ReceiptDeposit")
	proto.RegisterType((*ReceiptWithdraw)(nil), "types.ReceiptWithdraw")
	proto.RegisterType((*ReceiptClose)(nil), "types.ReceiptClose")
	proto.RegisterType((*ReceiptUpdate)(nil), "types.ReceiptUpdate")
	proto.RegisterType((*ReceiptSettle)(nil), "types.ReceiptSettle")
}

func init() { proto.RegisterFile("lns_contract.proto", fileDescriptor_lns_contract_3042a6b524479e87) }

var fileDescriptor_lns_contract_3042a6b524479e87 = []byte{
	// 1231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xaf, 0x9d, 0x38, 0xd9, 0xbc, 0x64, 0xdb, 0x32, 0xdb, 0x5d, 0x4c, 0x59, 0xa1, 0xca, 0x5a,
	0x41, 0x25, 0x96, 0x54, 0x4d, 0x11, 0x07, 0x04, 0x5a, 0x9a, 0x54, 0x22, 0x2b, 0x21, 0xba, 0x9a,
	0x16, 0x21, 0x71, 0x41, 0x53, 0x7b, 0xda, 0x58, 0xeb, 0xcc, 0x18, 0x7b, 0xb2, 0xa5, 0x37, 0xbe,
	0x00, 0x42, 0xdc, 0x10, 0x57, 0xb8, 0x22, 0x84, 0xb8, 0xf2, 0x45, 0x38, 0x70, 0xe3, 0xb0, 0x1f,
	0x03, 0x79, 0x66, 0x9c, 0x78, 0x6c, 0xb7, 0x89, 0xb4, 0x0b, 0xe2, 0xd4, 0xcc, 0x9b, 0xf7, 0x5e,
	0xde, 0xfc, 0xde, 0xef, 0xfd, 0x49, 0x01, 0x45, 0x2c, 0xfd, 0xd2, 0xe7, 0x4c, 0x24, 0xc4, 0x17,
	0xfd, 0x38, 0xe1, 0x82, 0x23, 0x47, 0x5c, 0xc5, 0x34, 0xdd, 0x7e, 0x45, 0x24, 0x84, 0xa5, 0xc4,
	0x17, 0x21, 0x67, 0xea, 0xc6, 0x7b, 0x6e, 0x43, 0xe7, 0x13, 0x96, 0x1e, 0x4a, 0x19, 0xda, 0x85,
	0x26, 0x8f, 0x29, 0x73, 0xad, 0x1d, 0x6b, 0xb7, 0x3b, 0x40, 0x7d, 0x69, 0xd6, 0x3f, 0x8e, 0x29,
	0x1b, 0x4d, 0x08, 0x63, 0x34, 0x1a, 0xaf, 0x61, 0xa9, 0x81, 0x1e, 0xc1, 0x7a, 0x40, 0x63, 0x9e,
	0x86, 0x42, 0xdf, 0xb8, 0xb6, 0xb4, 0xb9, 0xab, 0x6d, 0x8e, 0x8c, 0xcb, 0xf1, 0x1a, 0x2e, 0xa9,
	0xa3, 0x21, 0x6c, 0x5c, 0x86, 0x62, 0x12, 0x24, 0xe4, 0x32, 0xf7, 0xd0, 0x90, 0x1e, 0xee, 0x69,
	0x0f, 0x9f, 0x9b, 0xb7, 0xe3, 0x35, 0x5c, 0x36, 0x40, 0x6f, 0x83, 0xe3, 0x47, 0x3c, 0xa5, 0x6e,
	0x53, 0x5a, 0xde, 0xd1, 0x96, 0xa3, 0x4c, 0xb6, 0x30, 0x53, 0x3a, 0xe8, 0x43, 0xe8, 0xce, 0xe2,
	0x80, 0x08, 0xfa, 0x24, 0xe1, 0xfc, 0xdc, 0x75, 0xa4, 0xc9, 0x6b, 0xda, 0xe4, 0x33, 0x79, 0x33,
	0x24, 0x11, 0x61, 0xbe, 0x52, 0x18, 0xaf, 0xe1, 0xa2, 0x3e, 0x7a, 0x0b, 0x5a, 0x29, 0x15, 0x22,
	0xa2, 0x6e, 0x4b, 0x5a, 0xde, 0xd6, 0x96, 0x27, 0x52, 0x38, 0x5e, 0xc3, 0xfa, 0x1a, 0xad, 0x83,
	0x2d, 0xae, 0xdc, 0xf6, 0x8e, 0xb5, 0xeb, 0x60, 0x5b, 0x5c, 0x0d, 0xdb, 0xe0, 0x3c, 0x23, 0xd1,
	0x8c, 0x7a, 0x31, 0x6c, 0x9e, 0xf2, 0xa7, 0x94, 0x8d, 0x08, 0xe3, 0x2c, 0xf4, 0x49, 0xf4, 0x38,
	0x40, 0x5b, 0xe0, 0xf8, 0x13, 0x12, 0x2a, 0xc4, 0x3b, 0x58, 0x1d, 0xd0, 0x03, 0xb8, 0x1d, 0xa6,
	0xe9, 0x8c, 0x8e, 0x74, 0x16, 0x25, 0xb6, 0x1d, 0x6c, 0x0a, 0xd1, 0x0e, 0x74, 0x45, 0xe6, 0xef,
	0xe4, 0x6a, 0x7a, 0xc6, 0x15, 0x7a, 0x1d, 0x5c, 0x14, 0x79, 0xbf, 0x58, 0xd0, 0x2d, 0x24, 0xaf,
	0xea, 0xd7, 0x5a, 0xc1, 0xaf, 0x5d, 0xf1, 0x8b, 0x5c, 0x68, 0xc7, 0x24, 0x11, 0x8c, 0x26, 0xfa,
	0x5b, 0xf3, 0x63, 0xf6, 0x0d, 0x0a, 0x86, 0xd3, 0x70, 0x4a, 0xf9, 0x4c, 0xc8, 0xcc, 0x38, 0xd8,
	0x14, 0xa2, 0x7b, 0xd0, 0x22, 0x53, 0x3e, 0x63, 0x42, 0x66, 0xa1, 0x81, 0xf5, 0xc9, 0xc3, 0xb0,
	0x6e, 0xf2, 0x06, 0xdd, 0x87, 0x8e, 0xaf, 0x3e, 0x3e, 0x3e, 0x92, 0xd1, 0x36, 0xf0, 0x42, 0x80,
	0x3c, 0xe8, 0x09, 0x2e, 0x48, 0xa4, 0x8d, 0x64, 0xa8, 0x0d, 0x6c, 0xc8, 0xbc, 0xbf, 0x2d, 0xd8,
	0x28, 0x51, 0x69, 0x89, 0xd7, 0x7d, 0x70, 0x62, 0x49, 0x11, 0xc5, 0xe8, 0xd7, 0xcb, 0x7c, 0xe4,
	0xec, 0x3c, 0x4c, 0xa6, 0x92, 0x15, 0x58, 0x69, 0xa2, 0x0f, 0x60, 0x53, 0x23, 0x70, 0x12, 0x5e,
	0x30, 0x22, 0x66, 0x09, 0xd5, 0x6c, 0xde, 0xcc, 0x69, 0x92, 0xcb, 0x71, 0x45, 0x13, 0x0d, 0xe1,
	0x4e, 0xce, 0xec, 0xa2, 0x83, 0xe6, 0x35, 0x0e, 0xea, 0x94, 0xbd, 0x9f, 0x2d, 0xd8, 0xaa, 0x8b,
	0x70, 0xc9, 0x5b, 0xdf, 0x00, 0x58, 0x78, 0xd3, 0xa9, 0x2e, 0x48, 0xb2, 0x7c, 0x4a, 0x34, 0x73,
	0xd7, 0xf2, 0x55, 0x0d, 0x6c, 0x0a, 0xd1, 0x2e, 0x6c, 0xd0, 0xaf, 0xe3, 0x30, 0x21, 0x59, 0x13,
	0x19, 0x46, 0xdc, 0x7f, 0x2a, 0x83, 0x6f, 0xe0, 0xb2, 0xd8, 0xfb, 0xd6, 0x86, 0xed, 0xba, 0x30,
	0xb3, 0x87, 0xd0, 0x60, 0x49, 0xb0, 0xc7, 0xb0, 0x75, 0x59, 0x63, 0xbb, 0x4a, 0x9e, 0x6a, 0x0d,
	0xff, 0x07, 0x69, 0xfb, 0xc6, 0x82, 0xad, 0xd3, 0xac, 0x29, 0x9f, 0xd3, 0xe4, 0x30, 0x08, 0xc2,
	0x0c, 0xa9, 0x23, 0x22, 0x48, 0x86, 0x44, 0x4c, 0xae, 0xa6, 0x94, 0x09, 0x8d, 0x44, 0x07, 0x2f,
	0x04, 0x68, 0x1b, 0x6e, 0x25, 0xd4, 0xa7, 0xe1, 0xb3, 0x79, 0xd2, 0xe6, 0xe7, 0xac, 0xb8, 0x52,
	0xca, 0x82, 0x79, 0x6d, 0xea, 0x53, 0xa1, 0xe8, 0x9a, 0x46, 0xd1, 0xfd, 0x69, 0x41, 0xaf, 0xd8,
	0xf8, 0xb2, 0x9e, 0xc4, 0x38, 0xf3, 0xa9, 0x4e, 0x80, 0x3a, 0xa0, 0x87, 0xa0, 0xa6, 0xc7, 0x39,
	0x4d, 0x12, 0x1a, 0x1c, 0x2a, 0x4f, 0xaa, 0xe0, 0xaa, 0x17, 0x59, 0x65, 0x12, 0xfd, 0x9c, 0x31,
	0x49, 0x27, 0x32, 0x94, 0x1e, 0x36, 0x64, 0x68, 0x04, 0x9b, 0xa2, 0xd4, 0x0f, 0x35, 0x78, 0xaf,
	0x6a, 0xf0, 0xca, 0xed, 0x12, 0x57, 0x0c, 0x4c, 0xc6, 0x38, 0x25, 0xc6, 0x78, 0xbf, 0x5b, 0xd0,
	0x2b, 0x4e, 0x83, 0x25, 0x04, 0x1b, 0x01, 0x62, 0x9c, 0x49, 0x83, 0x24, 0x87, 0x24, 0xa7, 0x57,
	0x3e, 0x5c, 0x8a, 0x50, 0xe1, 0x1a, 0x75, 0xf4, 0x51, 0xc1, 0xc9, 0x72, 0x5a, 0xd5, 0xe8, 0x7a,
	0xbf, 0x59, 0x80, 0xaa, 0x03, 0x69, 0x49, 0xec, 0x8f, 0xe6, 0x5c, 0x5e, 0x29, 0xf2, 0x8a, 0xf2,
	0x8b, 0x15, 0x83, 0xf7, 0x83, 0x05, 0x2d, 0x35, 0x0a, 0x97, 0xc4, 0xf9, 0x2e, 0xdc, 0x4d, 0x69,
	0x74, 0x7e, 0x7a, 0x0d, 0x97, 0xea, 0x2f, 0xd1, 0xfb, 0xe0, 0xea, 0xaf, 0xac, 0x1a, 0xaa, 0x96,
	0x74, 0xed, 0xbd, 0xf7, 0xab, 0x05, 0xdd, 0x27, 0x24, 0x11, 0xa1, 0x1f, 0xc6, 0x84, 0x09, 0x84,
	0xa0, 0x49, 0x82, 0x20, 0xd1, 0x55, 0x25, 0x3f, 0xaf, 0x32, 0x49, 0x56, 0xec, 0x85, 0xf3, 0xea,
	0x69, 0x2e, 0xad, 0x1e, 0xe7, 0x9a, 0xea, 0xf1, 0xfe, 0xb2, 0xa1, 0xfd, 0xb2, 0x67, 0xb6, 0x91,
	0x95, 0x46, 0x39, 0x2b, 0xd2, 0x5e, 0x90, 0xe8, 0xb0, 0xd8, 0x21, 0x8a, 0xa2, 0xec, 0x5d, 0xa9,
	0x20, 0x82, 0xca, 0xa8, 0x1d, 0xac, 0x0e, 0xe8, 0x3d, 0xe8, 0xc5, 0x0b, 0x68, 0xf7, 0xf5, 0x6e,
	0x94, 0x2f, 0x8e, 0x05, 0xd4, 0xb1, 0xa1, 0x57, 0xb2, 0x1b, 0xc8, 0x75, 0x69, 0xb9, 0xdd, 0x20,
	0x6b, 0x62, 0x72, 0x9b, 0x4b, 0xdc, 0x5b, 0xaa, 0xb9, 0xa9, 0x53, 0x86, 0xaf, 0x5a, 0x31, 0xe4,
	0x98, 0x19, 0xd3, 0xf0, 0x62, 0x22, 0xdc, 0x8e, 0xc2, 0xb7, 0x72, 0xe1, 0x3d, 0x80, 0x9e, 0x86,
	0x77, 0x94, 0xbf, 0xcd, 0x97, 0xef, 0xd6, 0x1d, 0x4f, 0x1e, 0xbc, 0x77, 0xe0, 0x36, 0xa6, 0x5f,
	0x7d, 0x4c, 0x57, 0x5b, 0x46, 0xbc, 0xef, 0x6d, 0xe8, 0xe2, 0xac, 0x09, 0xc7, 0x22, 0xdb, 0xb9,
	0xb2, 0x50, 0xb3, 0x4d, 0x99, 0xe6, 0x44, 0xd3, 0xa7, 0xe2, 0xf2, 0x64, 0x9b, 0xcb, 0xd3, 0xcd,
	0x29, 0x7a, 0x13, 0xd6, 0x43, 0x16, 0x8a, 0x90, 0x44, 0xba, 0x66, 0x75, 0x96, 0x4a, 0x52, 0xed,
	0x25, 0x64, 0x9f, 0x92, 0xa9, 0x4a, 0x56, 0x07, 0x2f, 0x04, 0x55, 0x3a, 0xb5, 0xae, 0xa1, 0xd3,
	0x69, 0x81, 0x4e, 0x6d, 0x45, 0xa7, 0x82, 0xc8, 0x5c, 0xf4, 0x8e, 0x67, 0x42, 0xe6, 0xc3, 0x58,
	0xf4, 0x8e, 0x67, 0xc2, 0x7b, 0x6e, 0xc1, 0xba, 0xc6, 0x24, 0xaf, 0xa2, 0x7f, 0x75, 0xe3, 0x35,
	0x21, 0x6c, 0x2e, 0xdb, 0x17, 0x9d, 0x9a, 0x2a, 0xbf, 0x0f, 0x1d, 0xfd, 0x4b, 0x85, 0x27, 0x1a,
	0x9c, 0x85, 0xa0, 0x98, 0xbc, 0xb6, 0x91, 0x3c, 0xef, 0x3b, 0x0b, 0x36, 0xf4, 0x53, 0xe7, 0xbd,
	0xe0, 0xe6, 0x4e, 0x58, 0xe9, 0x27, 0x76, 0x5d, 0x3f, 0x31, 0x37, 0xb4, 0x66, 0x65, 0x43, 0x2b,
	0x44, 0xe4, 0x98, 0x11, 0xfd, 0x64, 0x41, 0x4f, 0x47, 0x24, 0x27, 0x4c, 0xed, 0xc0, 0xb5, 0x5e,
	0x68, 0xe0, 0xda, 0xe5, 0x37, 0x2d, 0xea, 0xb3, 0x61, 0xd4, 0x67, 0x21, 0xca, 0xa6, 0x19, 0xe5,
	0x1f, 0x56, 0x56, 0x66, 0x32, 0x4a, 0x35, 0xf3, 0x5e, 0x4e, 0x98, 0x2e, 0xb4, 0xd5, 0xaf, 0xb7,
	0x79, 0x95, 0xe9, 0xe3, 0x0d, 0x3f, 0x5e, 0x6e, 0x26, 0xcf, 0xbc, 0xb1, 0x3b, 0x85, 0xc6, 0xee,
	0xfd, 0x68, 0xcf, 0xc3, 0xd7, 0xe3, 0xef, 0x3f, 0x40, 0xd9, 0x2b, 0x75, 0x5d, 0xf5, 0x0e, 0xb3,
	0xc3, 0xf6, 0x01, 0x55, 0x06, 0xcb, 0xbe, 0x7e, 0x55, 0xcd, 0x4d, 0xc9, 0xe7, 0x40, 0x93, 0xc9,
	0xec, 0xbe, 0x75, 0x3e, 0x07, 0xb2, 0x48, 0xea, 0x7c, 0x0e, 0x86, 0xfd, 0x2f, 0x1e, 0x5e, 0x84,
	0x62, 0x32, 0x3b, 0xeb, 0xfb, 0x7c, 0xba, 0x77, 0x70, 0xe0, 0xb3, 0xbd, 0x38, 0x9a, 0x5d, 0x84,
	0xf3, 0x3f, 0x01, 0x89, 0xe3, 0xbd, 0x88, 0xa5, 0x7b, 0x12, 0x98, 0xb3, 0x96, 0xfc, 0x9f, 0xc4,
	0xc1, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xa3, 0x7e, 0x9b, 0xc3, 0x10, 0x00, 0x00,
}
